# Generated by Django 5.2.12 on 2026-03-08 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_company_tenant'),
        ('inventory', '0002_inventoryitem_tenant_warehouse_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=100, verbose_name='Customer PO Number')),
                ('so_number', models.CharField(blank=True, max_length=100, verbose_name='SO Number')),
                ('shipping_terms', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('total_weight_target', models.DecimalField(decimal_places=2, help_text='Target weight in lbs', max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_destination', to='inventory.warehouse')),
                ('receiver', models.ForeignKey(limit_choices_to={'company_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_receiver', to='accounts.company')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_orders', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_source', to='inventory.warehouse')),
                ('supplier', models.ForeignKey(limit_choices_to={'company_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supplier', to='accounts.company')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight_unit', models.CharField(default='lbs', max_length=10)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buy_price_unit', models.CharField(default='per lbs', max_length=20)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sell_price_unit', models.CharField(default='per lbs', max_length=20)),
                ('packaging', models.CharField(blank=True, max_length=100)),
                ('is_palletized', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_items', to='orders.order')),
            ],
        ),
    ]
