# Generated by Django 5.2.12 on 2026-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='secondary', help_text='Bootstrap color class (primary, success, danger, warning, info, secondary)', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_terms',
            field=models.CharField(blank=True, choices=[('FOB Destination', 'FOB Destination'), ('FOB Shipping Point', 'FOB Shipping Point'), ('EXW', 'EXW (Ex Works)'), ('CIF', 'CIF (Cost, Insurance & Freight)'), ('CFR', 'CFR (Cost & Freight)'), ('DAP', 'DAP (Delivered at Place)'), ('DDP', 'DDP (Delivered Duty Paid)')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.tag'),
        ),
    ]
