# Generated by Django 5.2.12 on 2026-03-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_tenant'),
        ('orders', '0005_packagingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingterm',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='shippingterm',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='shippingterm',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tenant', 'name')},
        ),
    ]
