# Generated by Django 5.2.12 on 2026-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shippingterm_tenant_tag_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
