# Generated by Django 5.2.12 on 2026-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_receiver_alter_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total estimated freight shipment cost', max_digits=12),
        ),
    ]
