# Generated by Django 5.2.12 on 2026-04-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_weight_unit',
            field=models.CharField(choices=[('lbs', 'lbs'), ('kgs', 'kgs'), ('mt', 'MT'), ('st', 'ST'), ('pcs', 'pcs')], default='lbs', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight_target',
            field=models.DecimalField(decimal_places=2, help_text='Target weight in the selected unit', max_digits=15),
        ),
    ]
