# Generated by Django 5.2.12 on 2026-04-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventorytransaction_transaction_type'),
        ('orders', '0012_order_total_weight_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_items', to='inventory.inventoryitem'),
        ),
    ]
