# Generated by Django 5.2.12 on 2026-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_manifestitem_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestitem',
            name='buy_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total estimated freight shipment cost', max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight_target',
            field=models.DecimalField(decimal_places=2, help_text='Target weight in the selected unit', max_digits=20),
        ),
    ]
