# Generated by Django 5.2.12 on 2026-03-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
