# Generated by Django 5.2.12 on 2026-03-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for the setting (e.g. 'wholesale_recipient')", max_length=100, unique=True)),
                ('value', models.TextField(help_text='The value of the setting')),
                ('description', models.CharField(blank=True, help_text='What this setting controls', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
