# Generated by Django 5.2.12 on 2026-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wholesalerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalerequest',
            name='desired_username',
            field=models.CharField(help_text='5 to 15 characters, must not start with a number', max_length=15),
        ),
    ]
