# Generated by Django 5.2.12 on 2026-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_wholesalerequest_desired_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalerequest',
            name='wholesaler_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
