# Generated by Django 5.2.12 on 2026-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_companyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_contact_archived',
            field=models.BooleanField(default=False),
        ),
    ]
