# Generated by Django 5.2.12 on 2026-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_is_contact_archived'),
        ('inventory', '0017_material_is_archived'),
        ('orders', '0012_order_total_weight_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_tags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='orders.tag'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='material_tags',
            field=models.ManyToManyField(blank=True, related_name='associated_companies', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='company',
            name='services_provided',
            field=models.JSONField(blank=True, default=list, help_text='List of services provided'),
        ),
    ]
