# Generated by Django 5.2.12 on 2026-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_company_tags_company_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crm_status',
            field=models.CharField(choices=[('active', 'Active'), ('cold', 'Cold'), ('dormant', 'Dormant'), ('lead', 'Lead')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='last_touch',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='next_touch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
