# Generated by Django 5.2.12 on 2026-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('warehouse', 'Warehouse Staff'), ('sales', 'Sales')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('warehouse', 'Warehouse Staff'), ('sales', 'Sales')], default='sales', max_length=20),
        ),
    ]
