# Generated by Django 5.2.13 on 2026-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Internal Administrator'), ('tenant_admin', 'Tenant Administrator'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Internal Administrator'), ('tenant_admin', 'Tenant Administrator'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
