# Generated by Django 5.2.12 on 2026-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_role_alter_teaminvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
