# Generated by Django 5.2.13 on 2026-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_teaminvitation_first_name_teaminvitation_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional')], default='basic', max_length=20),
        ),
    ]
