# Generated by Django 6.0.2 on 2026-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in lbs', max_digits=10)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H in inches', max_length=100)),
                ('shipment_type', models.CharField(choices=[('ftl', 'Full Truckload (FTL)'), ('ltl', 'Less Than Truckload (LTL)'), ('partial', 'Partial Truckload')], default='ltl', max_length=20)),
                ('service_level', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('expedited', 'Expedited')], default='standard', max_length=20)),
                ('carrier_name', models.CharField(max_length=100)),
                ('carrier_logo', models.CharField(blank=True, max_length=100)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transit_days_min', models.IntegerField(default=1)),
                ('transit_days_max', models.IntegerField(default=5)),
                ('quoted_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_best_rate', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-quoted_date', 'total_cost'],
            },
        ),
    ]
