# Generated by Django 5.2.12 on 2026-03-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_tenant'),
        ('inventory', '0002_inventoryitem_tenant_warehouse_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this location belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.company'),
        ),
    ]
