# Generated by Django 5.2.12 on 2026-03-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_subscription'),
        ('inventory', '0003_warehouse_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('material_type', models.CharField(blank=True, help_text='e.g. PE, PP, PVC', max_length=100)),
                ('grade', models.CharField(blank=True, help_text='e.g. Post-Industrial, Virgin', max_length=100)),
                ('color', models.CharField(blank=True, help_text='e.g. Mixed, Clear, White', max_length=100)),
                ('product_type', models.CharField(blank=True, help_text='e.g. Film, Flake, Regrind', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
