# Generated by Django 5.2.12 on 2026-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_subscription'),
        ('inventory', '0004_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('tenant', 'name')},
        ),
    ]
