# Generated by Django 5.2.12 on 2026-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_material_name_alter_material_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_storage',
            field=models.BooleanField(default=True, help_text="If False, this is a temporary order location and won't show in Inventory."),
        ),
    ]
