# Generated by Django 5.2.12 on 2026-03-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_subscription'),
        ('inventory', '0006_warehouse_is_storage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'code')},
        ),
    ]
