# Generated by Django 5.2.12 on 2026-03-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_coordinates'),
        ('inventory', '0008_alter_warehouse_code'),
        ('orders', '0011_orderdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_palletized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='packaging',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pieces',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='PO Number'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_unit',
            field=models.CharField(default='per lbs', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shipping_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='orders.shippingterm'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='inventory_items', to='orders.tag'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Minimum quantity before reorder', max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_of_measure',
            field=models.CharField(default='lbs', max_length=50),
        ),
    ]
