# Generated by Django 5.2.12 on 2026-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryitem_company_inventoryitem_is_palletized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Minimum quantity before reorder', max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
