# Generated by Django 5.2.12 on 2026-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='delivery_appointment_type',
            field=models.CharField(choices=[('fcfs', 'FCFS'), ('required', 'Required')], default='fcfs', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_remit_to',
            field=models.BooleanField(default=False, verbose_name='Remit To'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pickup_appointment_type',
            field=models.CharField(choices=[('fcfs', 'FCFS'), ('required', 'Required')], default='fcfs', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shipping_requirements',
            field=models.TextField(blank=True, help_text='Specific requirements for this location'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
