# Generated by Django 5.2.12 on 2026-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_warehouse_delivery_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='materials/docs/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/images/'),
        ),
    ]
