# Generated by Django 5.2.12 on 2026-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_material_document_alter_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='delivery_appointment_type',
            field=models.CharField(blank=True, choices=[('fcfs', 'FCFS'), ('required', 'Required')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='pickup_appointment_type',
            field=models.CharField(blank=True, choices=[('fcfs', 'FCFS'), ('required', 'Required')], max_length=20, null=True),
        ),
    ]
