# Generated by Django 5.2.12 on 2026-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_appointment_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='offered_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='offered_weight_unit',
            field=models.CharField(default='lbs', max_length=50),
        ),
    ]
