# Generated by Django 5.2.12 on 2026-04-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_created_by'),
        ('inventory', '0014_inventoryitem_offered_weight_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='material',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this material belongs to (optional, null means global to tenant)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('tenant', 'company', 'name')},
        ),
    ]
