# Generated by Django 5.2.12 on 2026-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_material_unique_together_material_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
