# Generated by Django 5.2.12 on 2026-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventoryitem_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
