# Generated by Django 5.2.12 on 2026-04-13 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_crm_status_company_last_touch_and_more'),
        ('inventory', '0017_material_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Inbound Receipt'), ('SHIP', 'Outbound Shipment'), ('ADJUST', 'Manual Adjustment'), ('INITIAL', 'Initial Stock')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Amount changed (positive or negative)', max_digits=20)),
                ('new_quantity', models.DecimalField(decimal_places=2, help_text='Quantity after the transaction', max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='accounts.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
