# Generated by Django 5.2.12 on 2026-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
