# Generated by Django 5.2.12 on 2026-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventoryitem_reserved_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIVE', 'Inbound Receipt'), ('SHIP', 'Outbound Shipment'), ('ADJUST', 'Manual Adjustment'), ('INITIAL', 'Initial Stock'), ('RESERVE', 'Inventory Reservation'), ('UNRESERVE', 'Reservation Released')], max_length=20),
        ),
    ]
