# Generated by Django 5.2.12 on 2026-04-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inventoryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='billing_preference',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
