# Generated by Django 5.2.12 on 2026-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Payment instructions for customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_details',
            field=models.TextField(blank=True, help_text='Tax details and information'),
        ),
    ]
