# Generated by Django 5.2.12 on 2026-03-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoice_file_name_invoice_payment_instructions_and_more'),
        ('shipments', '0007_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='shipments.shipment', unique=True),
        ),
    ]
