# Generated by Django 5.2.12 on 2026-04-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_alter_invoice_status_creditmemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='portal_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
