# Generated by Django 5.2.12 on 2026-04-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_invoice_portal_token'),
        ('shipments', '0019_shipmentcommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='shipments.shipment'),
        ),
    ]
