# Generated by Django 6.0.2 on 2026-02-17 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('booking_number', models.CharField(blank=True, max_length=100)),
                ('shipment_type', models.CharField(choices=[('ocean', 'Ocean Freight'), ('air', 'Air Freight'), ('road', 'Road Freight'), ('rail', 'Rail Freight')], default='road', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('customs', 'In Customs'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('origin_address', models.CharField(blank=True, max_length=255)),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('origin_state', models.CharField(blank=True, max_length=100)),
                ('origin_country', models.CharField(blank=True, default='USA', max_length=100)),
                ('origin_postal_code', models.CharField(blank=True, max_length=20)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('destination_state', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.CharField(blank=True, default='USA', max_length=100)),
                ('destination_postal_code', models.CharField(blank=True, max_length=20)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=12)),
                ('total_volume', models.DecimalField(decimal_places=4, default=0, help_text='Volume in cubic meters', max_digits=12)),
                ('number_of_pieces', models.IntegerField(default=1)),
                ('commodity_description', models.TextField(blank=True)),
                ('is_hazmat', models.BooleanField(default=False, verbose_name='Hazardous Materials')),
                ('is_temperature_controlled', models.BooleanField(default=False)),
                ('requires_insurance', models.BooleanField(default=False)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, limit_choices_to={'company_type': 'carrier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_carrier', to='accounts.company')),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_consignee', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'company_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_as_customer', to='accounts.company')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_as_shipper', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bol', 'Bill of Lading'), ('commercial_invoice', 'Commercial Invoice'), ('packing_list', 'Packing List'), ('customs', 'Customs Document'), ('certificate', 'Certificate'), ('insurance', 'Insurance Document'), ('pod', 'Proof of Delivery'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='shipment_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=50)),
                ('seal_number', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(choices=[('20ft', '20 ft Standard'), ('40ft', '40 ft Standard'), ('40hc', '40 ft High Cube'), ('45ft', '45 ft High Cube')], default='40ft', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=12)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='shipments.shipment')),
            ],
            options={
                'ordering': ['container_number'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Milestone',
                'verbose_name_plural': 'Shipment Milestones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
