# Generated by Django 5.2.12 on 2026-03-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_appointment',
            field=models.CharField(blank=True, choices=[('', '—'), ('required', 'Required'), ('not_required', 'Not Required'), ('scheduled', 'Scheduled'), ('tbd', 'TBD')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_number',
            field=models.CharField(blank=True, help_text='Delivery reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_appointment',
            field=models.CharField(blank=True, choices=[('', '—'), ('required', 'Required'), ('not_required', 'Not Required'), ('scheduled', 'Scheduled'), ('tbd', 'TBD')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_number',
            field=models.CharField(blank=True, help_text='Pickup reference number', max_length=100),
        ),
    ]
