# Generated by Django 5.2.12 on 2026-03-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_logistics_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_appointment',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_contact_email',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_contact_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_contact_phone',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_appointment',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_contact_email',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_contact_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_contact_phone',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_number',
        ),
    ]
