# Generated by Django 5.2.12 on 2026-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_remove_shipment_delivery_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
