# Generated by Django 5.2.12 on 2026-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('booked', 'Booked'), ('dispatched', 'Dispatched'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('customs', 'Customs'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
