# Generated by Django 5.2.12 on 2026-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_alter_shipment_status'),
    ]

    operations = []
