# Generated by Codex on 2026-03-20

from django.db import migrations


LEGACY_COLUMNS = [
    'buy_price',
    'buy_price_unit',
    'gross_weight',
    'gross_weight_unit',
    'is_packaging_palletized',
    'material_name',
    'net_weight',
    'net_weight_unit',
    'packaging_type',
    'sell_price',
    'sell_price_unit',
    'tare_weight',
    'tare_weight_unit',
]


def drop_legacy_columns(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        return

    table_name = 'shipments_shipment'
    with schema_editor.connection.cursor() as cursor:
        existing = {
            row.name
            for row in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

        for column in LEGACY_COLUMNS:
            if column not in existing:
                continue
            cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN "{column}"')


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_shipment_buy_price_shipment_buy_price_unit_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_columns, migrations.RunPython.noop),
    ]
