# Generated by Django 5.2.12 on 2026-03-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_warehouse_code'),
        ('shipments', '0011_drop_legacy_shipment_cargo_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_appointment_type',
            field=models.CharField(choices=[('fcfs', 'FCFS'), ('required', 'Required')], default='fcfs', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipments', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_appointment_type',
            field=models.CharField(choices=[('fcfs', 'FCFS'), ('required', 'Required')], default='fcfs', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_shipments', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
