# Generated by Django 5.2.12 on 2026-03-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_warehouse_code'),
        ('orders', '0010_orderevent'),
        ('shipments', '0012_shipment_delivery_appointment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.shippingterm'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='orders.tag'),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight_unit', models.CharField(default='lbs', max_length=10)),
                ('packaging', models.CharField(blank=True, max_length=100)),
                ('is_palletized', models.BooleanField(default=False)),
                ('pieces', models.IntegerField(blank=True, default=1, null=True)),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('price_unit', models.CharField(default='per lbs', max_length=20)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='inventory.inventoryitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
