# Generated by Django 5.2.12 on 2026-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_shipment_representative_shipment_shipping_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
