# Generated by Django 5.2.12 on 2026-03-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_shipment_delivery_email_shipment_pickup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='gross_weight_unit',
            field=models.CharField(blank=True, default='lbs', max_length=10),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='tare_weight_unit',
            field=models.CharField(blank=True, default='lbs', max_length=10),
        ),
    ]
