# Generated by Django 5.2.12 on 2026-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_shipmentitem_gross_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
