# Generated by Django 5.2.12 on 2026-04-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_shipmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shipments.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment Comment',
                'verbose_name_plural': 'Shipment Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
