# Generated by Django 5.2.12 on 2026-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_shipmentcommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quoted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_volume',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Volume in cubic meters', max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipmentcommission',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='buy_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
