# Generated by Django 5.2.12 on 2026-04-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_pendinginventoryemail_fetched_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginventoryemail',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='smartmatch',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
